include: package:pedantic/analysis_options.yaml

analyzer:
  exclude: [.*/**, build/**] # https://github.com/dart-lang/sdk/issues/33112
  errors:
    uri_has_not_been_generated: ignore
  plugins:
    - angular
  strong-mode:
    implicit-casts: false
#    implicit-dynamic: false

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
